# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/.build

# Include any dependencies generated for this target.
include CMakeFiles/../teelol.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/../teelol.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/../teelol.dir/flags.make

CMakeFiles/../teelol.dir/main.yr.o: CMakeFiles/../teelol.dir/flags.make
CMakeFiles/../teelol.dir/main.yr.o: ../main.yr
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/.build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building C object CMakeFiles/../teelol.dir/main.yr.o"
	gyc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../teelol.dir/main.yr.o   -c /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/main.yr

CMakeFiles/../teelol.dir/main.yr.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../teelol.dir/main.yr.i"
	gyc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/main.yr > CMakeFiles/../teelol.dir/main.yr.i

CMakeFiles/../teelol.dir/main.yr.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../teelol.dir/main.yr.s"
	gyc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/main.yr -o CMakeFiles/../teelol.dir/main.yr.s

CMakeFiles/../teelol.dir/main.yr.o.requires:

.PHONY : CMakeFiles/../teelol.dir/main.yr.o.requires

CMakeFiles/../teelol.dir/main.yr.o.provides: CMakeFiles/../teelol.dir/main.yr.o.requires
	$(MAKE) -f CMakeFiles/../teelol.dir/build.make CMakeFiles/../teelol.dir/main.yr.o.provides.build
.PHONY : CMakeFiles/../teelol.dir/main.yr.o.provides

CMakeFiles/../teelol.dir/main.yr.o.provides.build: CMakeFiles/../teelol.dir/main.yr.o


CMakeFiles/../teelol.dir/src/eventHandler.yr.o: CMakeFiles/../teelol.dir/flags.make
CMakeFiles/../teelol.dir/src/eventHandler.yr.o: ../src/eventHandler.yr
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/.build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building C object CMakeFiles/../teelol.dir/src/eventHandler.yr.o"
	gyc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../teelol.dir/src/eventHandler.yr.o   -c /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/src/eventHandler.yr

CMakeFiles/../teelol.dir/src/eventHandler.yr.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../teelol.dir/src/eventHandler.yr.i"
	gyc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/src/eventHandler.yr > CMakeFiles/../teelol.dir/src/eventHandler.yr.i

CMakeFiles/../teelol.dir/src/eventHandler.yr.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../teelol.dir/src/eventHandler.yr.s"
	gyc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/src/eventHandler.yr -o CMakeFiles/../teelol.dir/src/eventHandler.yr.s

CMakeFiles/../teelol.dir/src/eventHandler.yr.o.requires:

.PHONY : CMakeFiles/../teelol.dir/src/eventHandler.yr.o.requires

CMakeFiles/../teelol.dir/src/eventHandler.yr.o.provides: CMakeFiles/../teelol.dir/src/eventHandler.yr.o.requires
	$(MAKE) -f CMakeFiles/../teelol.dir/build.make CMakeFiles/../teelol.dir/src/eventHandler.yr.o.provides.build
.PHONY : CMakeFiles/../teelol.dir/src/eventHandler.yr.o.provides

CMakeFiles/../teelol.dir/src/eventHandler.yr.o.provides.build: CMakeFiles/../teelol.dir/src/eventHandler.yr.o


CMakeFiles/../teelol.dir/src/game.yr.o: CMakeFiles/../teelol.dir/flags.make
CMakeFiles/../teelol.dir/src/game.yr.o: ../src/game.yr
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/.build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building C object CMakeFiles/../teelol.dir/src/game.yr.o"
	gyc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../teelol.dir/src/game.yr.o   -c /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/src/game.yr

CMakeFiles/../teelol.dir/src/game.yr.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../teelol.dir/src/game.yr.i"
	gyc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/src/game.yr > CMakeFiles/../teelol.dir/src/game.yr.i

CMakeFiles/../teelol.dir/src/game.yr.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../teelol.dir/src/game.yr.s"
	gyc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/src/game.yr -o CMakeFiles/../teelol.dir/src/game.yr.s

CMakeFiles/../teelol.dir/src/game.yr.o.requires:

.PHONY : CMakeFiles/../teelol.dir/src/game.yr.o.requires

CMakeFiles/../teelol.dir/src/game.yr.o.provides: CMakeFiles/../teelol.dir/src/game.yr.o.requires
	$(MAKE) -f CMakeFiles/../teelol.dir/build.make CMakeFiles/../teelol.dir/src/game.yr.o.provides.build
.PHONY : CMakeFiles/../teelol.dir/src/game.yr.o.provides

CMakeFiles/../teelol.dir/src/game.yr.o.provides.build: CMakeFiles/../teelol.dir/src/game.yr.o


CMakeFiles/../teelol.dir/src/lib/sdl.yr.o: CMakeFiles/../teelol.dir/flags.make
CMakeFiles/../teelol.dir/src/lib/sdl.yr.o: ../src/lib/sdl.yr
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/.build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building C object CMakeFiles/../teelol.dir/src/lib/sdl.yr.o"
	gyc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../teelol.dir/src/lib/sdl.yr.o   -c /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/src/lib/sdl.yr

CMakeFiles/../teelol.dir/src/lib/sdl.yr.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../teelol.dir/src/lib/sdl.yr.i"
	gyc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/src/lib/sdl.yr > CMakeFiles/../teelol.dir/src/lib/sdl.yr.i

CMakeFiles/../teelol.dir/src/lib/sdl.yr.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../teelol.dir/src/lib/sdl.yr.s"
	gyc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/src/lib/sdl.yr -o CMakeFiles/../teelol.dir/src/lib/sdl.yr.s

CMakeFiles/../teelol.dir/src/lib/sdl.yr.o.requires:

.PHONY : CMakeFiles/../teelol.dir/src/lib/sdl.yr.o.requires

CMakeFiles/../teelol.dir/src/lib/sdl.yr.o.provides: CMakeFiles/../teelol.dir/src/lib/sdl.yr.o.requires
	$(MAKE) -f CMakeFiles/../teelol.dir/build.make CMakeFiles/../teelol.dir/src/lib/sdl.yr.o.provides.build
.PHONY : CMakeFiles/../teelol.dir/src/lib/sdl.yr.o.provides

CMakeFiles/../teelol.dir/src/lib/sdl.yr.o.provides.build: CMakeFiles/../teelol.dir/src/lib/sdl.yr.o


CMakeFiles/../teelol.dir/src/lib/signal.yr.o: CMakeFiles/../teelol.dir/flags.make
CMakeFiles/../teelol.dir/src/lib/signal.yr.o: ../src/lib/signal.yr
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/.build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building C object CMakeFiles/../teelol.dir/src/lib/signal.yr.o"
	gyc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../teelol.dir/src/lib/signal.yr.o   -c /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/src/lib/signal.yr

CMakeFiles/../teelol.dir/src/lib/signal.yr.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../teelol.dir/src/lib/signal.yr.i"
	gyc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/src/lib/signal.yr > CMakeFiles/../teelol.dir/src/lib/signal.yr.i

CMakeFiles/../teelol.dir/src/lib/signal.yr.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../teelol.dir/src/lib/signal.yr.s"
	gyc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/src/lib/signal.yr -o CMakeFiles/../teelol.dir/src/lib/signal.yr.s

CMakeFiles/../teelol.dir/src/lib/signal.yr.o.requires:

.PHONY : CMakeFiles/../teelol.dir/src/lib/signal.yr.o.requires

CMakeFiles/../teelol.dir/src/lib/signal.yr.o.provides: CMakeFiles/../teelol.dir/src/lib/signal.yr.o.requires
	$(MAKE) -f CMakeFiles/../teelol.dir/build.make CMakeFiles/../teelol.dir/src/lib/signal.yr.o.provides.build
.PHONY : CMakeFiles/../teelol.dir/src/lib/signal.yr.o.provides

CMakeFiles/../teelol.dir/src/lib/signal.yr.o.provides.build: CMakeFiles/../teelol.dir/src/lib/signal.yr.o


CMakeFiles/../teelol.dir/src/player.yr.o: CMakeFiles/../teelol.dir/flags.make
CMakeFiles/../teelol.dir/src/player.yr.o: ../src/player.yr
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/.build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Building C object CMakeFiles/../teelol.dir/src/player.yr.o"
	gyc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../teelol.dir/src/player.yr.o   -c /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/src/player.yr

CMakeFiles/../teelol.dir/src/player.yr.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../teelol.dir/src/player.yr.i"
	gyc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/src/player.yr > CMakeFiles/../teelol.dir/src/player.yr.i

CMakeFiles/../teelol.dir/src/player.yr.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../teelol.dir/src/player.yr.s"
	gyc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/src/player.yr -o CMakeFiles/../teelol.dir/src/player.yr.s

CMakeFiles/../teelol.dir/src/player.yr.o.requires:

.PHONY : CMakeFiles/../teelol.dir/src/player.yr.o.requires

CMakeFiles/../teelol.dir/src/player.yr.o.provides: CMakeFiles/../teelol.dir/src/player.yr.o.requires
	$(MAKE) -f CMakeFiles/../teelol.dir/build.make CMakeFiles/../teelol.dir/src/player.yr.o.provides.build
.PHONY : CMakeFiles/../teelol.dir/src/player.yr.o.provides

CMakeFiles/../teelol.dir/src/player.yr.o.provides.build: CMakeFiles/../teelol.dir/src/player.yr.o


CMakeFiles/../teelol.dir/src/screen.yr.o: CMakeFiles/../teelol.dir/flags.make
CMakeFiles/../teelol.dir/src/screen.yr.o: ../src/screen.yr
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/.build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Building C object CMakeFiles/../teelol.dir/src/screen.yr.o"
	gyc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../teelol.dir/src/screen.yr.o   -c /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/src/screen.yr

CMakeFiles/../teelol.dir/src/screen.yr.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../teelol.dir/src/screen.yr.i"
	gyc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/src/screen.yr > CMakeFiles/../teelol.dir/src/screen.yr.i

CMakeFiles/../teelol.dir/src/screen.yr.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../teelol.dir/src/screen.yr.s"
	gyc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/src/screen.yr -o CMakeFiles/../teelol.dir/src/screen.yr.s

CMakeFiles/../teelol.dir/src/screen.yr.o.requires:

.PHONY : CMakeFiles/../teelol.dir/src/screen.yr.o.requires

CMakeFiles/../teelol.dir/src/screen.yr.o.provides: CMakeFiles/../teelol.dir/src/screen.yr.o.requires
	$(MAKE) -f CMakeFiles/../teelol.dir/build.make CMakeFiles/../teelol.dir/src/screen.yr.o.provides.build
.PHONY : CMakeFiles/../teelol.dir/src/screen.yr.o.provides

CMakeFiles/../teelol.dir/src/screen.yr.o.provides.build: CMakeFiles/../teelol.dir/src/screen.yr.o


# Object files for target ../teelol
__/teelol_OBJECTS = \
"CMakeFiles/../teelol.dir/main.yr.o" \
"CMakeFiles/../teelol.dir/src/eventHandler.yr.o" \
"CMakeFiles/../teelol.dir/src/game.yr.o" \
"CMakeFiles/../teelol.dir/src/lib/sdl.yr.o" \
"CMakeFiles/../teelol.dir/src/lib/signal.yr.o" \
"CMakeFiles/../teelol.dir/src/player.yr.o" \
"CMakeFiles/../teelol.dir/src/screen.yr.o"

# External object files for target ../teelol
__/teelol_EXTERNAL_OBJECTS =

../teelol: CMakeFiles/../teelol.dir/main.yr.o
../teelol: CMakeFiles/../teelol.dir/src/eventHandler.yr.o
../teelol: CMakeFiles/../teelol.dir/src/game.yr.o
../teelol: CMakeFiles/../teelol.dir/src/lib/sdl.yr.o
../teelol: CMakeFiles/../teelol.dir/src/lib/signal.yr.o
../teelol: CMakeFiles/../teelol.dir/src/player.yr.o
../teelol: CMakeFiles/../teelol.dir/src/screen.yr.o
../teelol: CMakeFiles/../teelol.dir/build.make
../teelol: CMakeFiles/../teelol.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/.build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_8) "Linking C executable ../teelol"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/../teelol.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/../teelol.dir/build: ../teelol

.PHONY : CMakeFiles/../teelol.dir/build

CMakeFiles/../teelol.dir/requires: CMakeFiles/../teelol.dir/main.yr.o.requires
CMakeFiles/../teelol.dir/requires: CMakeFiles/../teelol.dir/src/eventHandler.yr.o.requires
CMakeFiles/../teelol.dir/requires: CMakeFiles/../teelol.dir/src/game.yr.o.requires
CMakeFiles/../teelol.dir/requires: CMakeFiles/../teelol.dir/src/lib/sdl.yr.o.requires
CMakeFiles/../teelol.dir/requires: CMakeFiles/../teelol.dir/src/lib/signal.yr.o.requires
CMakeFiles/../teelol.dir/requires: CMakeFiles/../teelol.dir/src/player.yr.o.requires
CMakeFiles/../teelol.dir/requires: CMakeFiles/../teelol.dir/src/screen.yr.o.requires

.PHONY : CMakeFiles/../teelol.dir/requires

CMakeFiles/../teelol.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/../teelol.dir/cmake_clean.cmake
.PHONY : CMakeFiles/../teelol.dir/clean

CMakeFiles/../teelol.dir/depend:
	cd /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/.build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/.build /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/.build /home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/.build/teelol.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/../teelol.dir/depend

