# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

teelol.dir/main.yr.o: ../main.yr

teelol.dir/src/eventHandler.yr.o: ../src/eventHandler.yr

teelol.dir/src/game.yr.o: ../src/game.yr

teelol.dir/src/lib/sdl.yr.o: ../src/lib/sdl.yr

teelol.dir/src/lib/signal.yr.o: ../src/lib/signal.yr

teelol.dir/src/player.yr.o: ../src/player.yr

teelol.dir/src/screen.yr.o: ../src/screen.yr

