# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# compile C with gyc
C_FLAGS =  -g -fdump-tree-gimple  

C_DEFINES = 

C_INCLUDES = -I/home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/teelol -I/home/ggas/Documents/ymir/Ymir-Test/sdl/Teelol/. 

